repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        description: Prevent giant files from being committed
        entry: check-added-large-files
        language: python

      - id: check-ast
        name: Check python ast
        description: Simply check whether the files parse as valid python.
        entry: check-ast
        language: python
        types: [python]

      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems
        entry: check-case-conflict
        language: python

      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: python
        types: [text]

      - id: debug-statements
        name: Debug Statements (Python)
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
        entry: debug-statement-hook
        language: python
        types: [python]

      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

      - id: mixed-line-ending
        name: Mixed line ending
        description: Replaces or checks mixed line ending
        entry: mixed-line-ending
        language: python
        types: [text]

      - id: no-commit-to-branch
        name: "Don't commit to branch"
        entry: no-commit-to-branch
        language: python
        pass_filenames: false
        always_run: true

      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
        exclude: docs

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
      - id: flake8
        exclude: docs

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
        exclude: docs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        exclude: docs

  - repo: https://github.com/prettier/prettier
    rev: 2.1.1
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: install-dependencies
        name: Installing Dependencies
        entry: poetry install
        language: python
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        always_run: true
        pass_filenames: false
